FROM apache/airflow:3.1.0-python3.11
USER airflow
COPY --chown=airflow:root pyproject.toml README.md /opt/merchmind/
COPY --chown=airflow:root src /opt/merchmind/src
RUN pip install --no-cache-dir "apache-airflow==3.1.0" /opt/merchmind pytest
COPY --chown=airflow:root dags /opt/airflow/dags
COPY --chown=airflow:root scripts /opt/merchmind/scripts
COPY --chown=airflow:root tests /opt/merchmind/tests
